[package]
name = "refineid-x509"
description = "SubjectPublicKeyInfo extraction from FINEID X.509 certificates"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[lib]
doctest = false

[dependencies]
refineid-ber.workspace = true

[lints]
workspace = true
